import type { Metadata } from "next";
import { Source_Code_Pro } from "next/font/google";
import { ThemeProvider } from "next-themes";
import "./globals.css";
import { Header } from "@/components/Header/Header";

const sourceCodePro = Source_Code_Pro({
  variable: "--font-source-code-pro",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="scroll-smooth">
      <body
        className={`${sourceCodePro.variable} antialiased bg-background min-h-screen flex flex-col items-center`}
      >
        <ThemeProvider attribute={"class"} defaultTheme="dark">
          <Header />
          <main className="flex-1 flex grow w-full max-w-[800px] font-sans">
            {children}
          </main>
          <footer>Footer</footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
